[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default.csv
lib_extra_dirs =
  ../third_party

lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
  links2004/WebSockets @ ^2.4.1
  h2zero/NimBLE-Arduino @ ^2.2.3

build_flags =
  -D CORE_DEBUG_LEVEL=1

[env:esp32_wroom_32d]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D CONTROLLER_BOARD_WROOM=1
  -D CONTROLLER_BOARD_NAME=\"ESP32-WROOM-32D\"

[env:esp32_s3_devkitc_1]
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
build_flags =
  ${env.build_flags}
  -D CONTROLLER_BOARD_S3=1
  -D CONTROLLER_BOARD_NAME=\"ESP32-S3-DevKitC-1\"
