[env:esp32_wroom_32d]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default.csv
lib_extra_dirs =
  ../third_party

lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
  links2004/WebSockets @ ^2.4.1
  h2zero/NimBLE-Arduino @ ^2.2.3

build_flags =
  -D CORE_DEBUG_LEVEL=1
